/*
 *  *******************************************************************************
 *  Copyright (c) 2023-24 Harman International
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  SPDX-License-Identifier: Apache-2.0
 *  *******************************************************************************
 */

package org.eclipse.ecsp.service.swm;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.eclipse.ecsp.common.CommonConstants;
import org.eclipse.ecsp.common.config.EnvConfig;
import org.eclipse.ecsp.common.exception.ApiTechnicalException;
import org.eclipse.ecsp.config.DeviceInfoQueryProperty;
import org.eclipse.ecsp.dto.swm.SwmRequest;
import org.eclipse.ecsp.dto.swm.SwmVinRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;

import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.eclipse.ecsp.common.enums.ApiMessageEnum.SWM_SESSION_ID_NULL;

/**
 * This abstract class provides a base implementation for the SWM (Software Warehouse Management) CRUD service.
 * It contains common methods and properties used by SWM CRUD services.
 */
public abstract class AbstractSwmCrudService<I> implements IswmCrudService<I> {
    /**
     * A constant representing the identifier field name, typically used as a key
     * or reference for identifying entities in the system.
     */
    public static final String ID = "id";
    /**
     * A constant representing the key for accessing representation objects.
     * This key is typically used in contexts where objects are represented
     * in a specific format or structure.
     */
    public static final String REPRESENTATION_OBJECTS = "representationObjects";
    protected static final Logger LOGGER = LoggerFactory.getLogger(AbstractSwmCrudService.class);
    protected String loginUrl;
    protected String createVehicleUrl;
    protected String updateVehicleUrl;
    protected String deleteVehicleUrl;
    protected String vehicleModelsUrl;
    protected String vehiclesUrl;

    protected String swmUserName;
    protected String swmPassword;
    protected String swmDomain;
    protected String vehicleModelId;

    @Autowired
    protected EnvConfig<DeviceInfoQueryProperty> envConfig;

    @Autowired
    protected RestTemplate restTemplate;

    /**
     * Returns the session ID by generating a SWM session ID.
     *
     * @return the session ID generated by the SWM session ID generator
     */
    protected String findSessionId() {
        return generateSwmSessionId();
    }

    /**
     * Generates a SWM session ID by making a login API call to the SWM server.
     *
     * @return The generated SWM session ID.
     * @throws ApiTechnicalException If there is an error while generating the session ID.
     */
    private String generateSwmSessionId() {
        HttpEntity<String> entity = new HttpEntity<>(
            "&userName=" + swmUserName + "&password=" + swmPassword + "&domain=" + swmDomain + "&");
        String sessionId = "";
        try {
            LOGGER.debug("## Hitting swm login api: {} ", loginUrl);
            ResponseEntity<String> response = restTemplate.exchange(loginUrl, HttpMethod.POST, entity, String.class);
            LOGGER.debug("## Response code: {}, from: {}", response.getStatusCode(), loginUrl);
            if (response.getStatusCode() == HttpStatus.OK) {
                LOGGER.debug("## Got success from Login API");
                HashMap<String, Object> responseMap = new ObjectMapper().readValue(response.getBody(), HashMap.class);
                sessionId = responseMap.get("sessionId").toString();
                LOGGER.debug("## Session id from SWM: {}", sessionId);
            } else {
                LOGGER.error("## Error while getting session id , http status code :{} ",
                    response.getStatusCode().value());
                throw new ApiTechnicalException(SWM_SESSION_ID_NULL.getCode(), SWM_SESSION_ID_NULL.getMessage(),
                    SWM_SESSION_ID_NULL.getGeneralMessage());
            }
        } catch (RuntimeException ex) {
            LOGGER.error("generating swm session id failed.Error message: {}", ex.getMessage());
            throw new ApiTechnicalException(SWM_SESSION_ID_NULL.getCode(), SWM_SESSION_ID_NULL.getMessage(),
                SWM_SESSION_ID_NULL.getGeneralMessage());
        } catch (Exception e) {
            throw new ApiTechnicalException(SWM_SESSION_ID_NULL.getCode(), SWM_SESSION_ID_NULL.getMessage(),
                SWM_SESSION_ID_NULL.getGeneralMessage());
        }
        return sessionId;
    }

    /**
     * Calls the SWM Vehicle Model API to retrieve vehicle models.
     *
     * @param headers the HttpHeaders object containing the request headers
     * @return a ResponseEntity object containing the response from the API
     */
    protected ResponseEntity<String> callSwmVehicleModelApi(HttpHeaders headers) {
        return restTemplate.exchange(vehicleModelsUrl, HttpMethod.GET, new HttpEntity<>(headers), String.class);
    }

    /**
     * Finds the ID to delete and update the vehicle based on the given SwmRequest.
     *
     * @param swmRequest The SwmRequest object containing the necessary information.
     * @return The ID of the vehicle to delete and update, or null if not found.
     * @throws IOException If an I/O error occurs while making the request.
     */
    protected String findIdToDeleteAndUpdateVehicle(SwmRequest swmRequest) throws IOException {
        LOGGER.debug("## findIdToDeleteAndUpdateVehicle - START swmRequest: {}", swmRequest);
        SwmVinRequest swmVinRequest = (SwmVinRequest) swmRequest;
        HttpEntity<SwmVinRequest> entity = new HttpEntity<>(swmVinRequest, createHeaders(findSessionId()));
        ResponseEntity<String> response = restTemplate.exchange(vehiclesUrl, HttpMethod.POST, entity, String.class);
        HttpStatusCode statusCode = response.getStatusCode();
        LOGGER.debug("## Response code: {}, from: {}", statusCode, createVehicleUrl);
        String id;
        if (statusCode.value() == HttpStatus.OK.value()) {
            ObjectMapper mapper = new ObjectMapper();
            mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
            String res = response.getBody();
            ObjectMapper objectMapper = new ObjectMapper();
            objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
            HashMap<String, Object> responseMap = objectMapper.readValue(res, HashMap.class);
            List<Object> representationObjects = (List) responseMap.get(REPRESENTATION_OBJECTS);
            Map<String, Object> map = (Map) representationObjects.get(0);
            id = (String) map.get(ID);
        } else {
            LOGGER.warn("## Unable to find id from vehiclesUrl: {} from SWM, response StatusCode: {}", vehiclesUrl,
                statusCode.value());
            id = null;
        }
        LOGGER.debug("## findIdToDeleteAndUpdateVehicle - END id: {}", id);
        return id;
    }

    /**
     * Creates and returns the HttpHeaders object with the specified session ID.
     *
     * @param sessionId the session ID to be added to the headers
     * @return the HttpHeaders object with the specified session ID
     */
    protected HttpHeaders createHeaders(String sessionId) {
        HttpHeaders headers = new HttpHeaders();
        headers.add(CommonConstants.HEADER_CONTENT_TYPE_KEY, CommonConstants.APPLICATION_JSON);
        headers.add(CommonConstants.SESSIONID, sessionId);
        return headers;
    }
}
